// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfrTkS3EL7rrT_rdFrTjv6X7H8q_Ufr0g',
    appId: '1:358101611411:web:2e9ce482366062d1e1ee66',
    messagingSenderId: '358101611411',
    projectId: 'tophservices',
    authDomain: 'tophservices.firebaseapp.com',
    databaseURL: 'https://tophservices-default-rtdb.firebaseio.com',
    storageBucket: 'tophservices.appspot.com',
    measurementId: 'G-H8D0FPXWYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs6fnVHbcnanTDogP3wI_DDj5BuDzn34Y',
    appId: '1:358101611411:android:40833bd530ace7f0e1ee66',
    messagingSenderId: '358101611411',
    projectId: 'tophservices',
    databaseURL: 'https://tophservices-default-rtdb.firebaseio.com',
    storageBucket: 'tophservices.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFpm_6TNCLtCnTeSmGGagPenNOEiOPsug',
    appId: '1:358101611411:ios:84199615de82f942e1ee66',
    messagingSenderId: '358101611411',
    projectId: 'tophservices',
    databaseURL: 'https://tophservices-default-rtdb.firebaseio.com',
    storageBucket: 'tophservices.appspot.com',
    androidClientId: '358101611411-0kpn6i3sf61obri4rflnn3qrf2546dpt.apps.googleusercontent.com',
    iosClientId: '358101611411-450qmubqt7uunieighe7capeq7l307oc.apps.googleusercontent.com',
    iosBundleId: 'com.example.tophservices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFpm_6TNCLtCnTeSmGGagPenNOEiOPsug',
    appId: '1:358101611411:ios:b47e70c2717f8255e1ee66',
    messagingSenderId: '358101611411',
    projectId: 'tophservices',
    databaseURL: 'https://tophservices-default-rtdb.firebaseio.com',
    storageBucket: 'tophservices.appspot.com',
    androidClientId: '358101611411-0kpn6i3sf61obri4rflnn3qrf2546dpt.apps.googleusercontent.com',
    iosClientId: '358101611411-bnipl1bks613qsan71lbngq56qs2sjrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.tophservices.RunnerTests',
  );
}
